version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webhooks
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./alembic:/alembic
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: ["python", "-m", "app.worker"]
    depends_on:
      - app
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webhooks
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhooks
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: